title: Transaction API
version: v1
baseUri: http://bogdandm.ddns.net/{service}/api/{version}/
mediaType: application/json

documentation:
  - title: ""
    content: |
      Это API, поволяющий выпонять транзакции для REST-сервиса

/transaction:

