#%RAML 0.8
title: Transaction API
version: v1
baseUri: http://bogdandm.ddns.net/{service}/api/{version}/
mediaType: application/json

documentation:
  - title: ""
    content: |
      Это API, поволяющий выпонять транзакции для REST-сервиса

/transaction:
  post:
    description: |
      Открытие новой транзакции. Передаеются параметры транзакции (таймауты). Возращает имя сервиса и ключ данной транзакции.

  /{id}:
    post:
      description: |
        Commit. Передается ключ транзакции.

    delete:
      description: |
        Rollback. Передается ключ транзакции.

    get:
      description: |
        Ping. Должен вызываться каждые N мс. В случае задержки вызова на 2*N сервис считает соединение потерянным и происходит односторонний откат. Если сервис перестал отвечать на ping, то контроллер региструет разрыв соедениния и выполняет глобальный откат.
